Add RabbitMQConnector
hrimov/decision-making-app pull request #7
Opened 2024-01-17 13:54 UTC by lazorikv

Introduced the RabbitMQConnectorGateway for enhanced RabbitMQ integration. This includes new tests, and necessary Config model changes. The `publish`, `consume`, and queue management methods were added for the RabbitMQ interaction. A new `batched` helper was also added for batching messages during publishing. Configuration parsing logic and necessary dependencies were also updated.

2024-01-24 16:33 UTC, hrimov requested changes

2024-01-24 16:33 UTC, hrimov commented on src/app/application/rmq_connector/interfaces.py
> +class RabbitMQConnectorGateway(Protocol):
It cannot be the actual implementation, in the `application`, we must have the minimal interfaces to satisfy (implementations will be concrete). So, in this case it must be `MessageQueueGateway` with few methods that are not depend on the implementation, and the `RabbitMQGatewayImpl` must follow the contract of the `MessageQueueGateway` protocol with the needed modifications.

2024-01-24 16:33 UTC, hrimov commented on pyproject.toml
> +pika = "^1.3.2"
As you already added extras to the `testcontainers` dependency, I think this one is not necessary and should be removed.

2024-01-24 16:33 UTC, hrimov commented on src/app/infrastructure/config/models/rmq_connector.py
> +class RabbitMQConnectorConfig:
I think, that such config must be with the abstract name, e.g. `MessageQueueConfig`, as well as the `ObjectStorageConfig` and `DatabaseConfig`, just to be strict to the one style.

2024-01-24 16:33 UTC, hrimov commented on src/app/infrastructure/config/models/rmq_connector.py
> +        return f"amqp://{self.username}:{self.password}@{self.host}:{self.port}"
It would be better to have the prefix as a field, so it can be redefined in case of the another MQ in use, e.g.
```python
    ...
    connector_prefix: str = "amqp"  # or just `connector`

    def full_url(self) -> str:
         return f"{self.connector_prefix}://{self.username}:{self.password}@{self.host}:{self.port}"

```

2024-01-24 16:33 UTC, hrimov commented on src/app/infrastructure/rmq_connector/gateway.py
> +    BATCH_SIZE: int = 200
I think that such things should be also flexibly configured, for example with getting from the config / at the initialisation stage.

2024-01-24 16:33 UTC, hrimov commented on tests/integration/infrastructure/rmq_connector/conftest.py
> +    await gateway.shutdown()
It's better to make a cleanup without depending on the Gateway that you actually testing. In this way, I would use the provided client from the `testcontainers` (`pika`).

2024-02-21 11:16 UTC, hrimov approved these changes

2024-02-21 11:26 UTC, lazorikv commented
LЗБСTM!

2024-02-21 11:31 UTC, merged